/*
 * AdjTestPanel.java
 *
 * Created on March 3, 2002, 11:19 AM
 */

package champions.adjustmentPowers.adjustmentTree;

import champions.*;
import champions.interfaces.*;
import champions.powers.*;

import javax.swing.*;
import java.awt.*;
import java.beans.*;
/**
 *
 * @author  twalker
 */
public class AdjTestPanel extends javax.swing.JFrame {

    /** Creates new form AdjTestPanel */ 
    public AdjTestPanel() {
        initComponents();

        UIManager.put("Checked.DefaultIcon", new ImageIcon( getClass().getResource("/graphics/greenCheckIcon.gif")));
        UIManager.put("X.DefaultIcon", new ImageIcon( getClass().getResource("/graphics/redXIcon.gif")));

        Target source = new champions.Character("bob");
        Ability ability = new Ability("Aid");
        ability.addPAD( new powerAid(), null );
        
        int type = ChampionsConstants.ADJ_CONFIG_AID_TO;
        int level = ChampionsConstants.ADJ_VARIABLE_2_ADJUSTMENT;
        
        AdjTreeTable adjConfigSourceTree = new AdjTreeTable();
        jScrollPane1.setViewportView(adjConfigSourceTree);
        
        AdjConfigSourceModel model1 = new AdjConfigSourceModel(type, level, source);
        adjConfigSourceTree.setTreeTableModel( model1 );
        
       /* ParameterList pl = ability.getPower().getParameterList(ability, -1 );
        AdjConfigDestinationModel model2 = new AdjConfigDestinationModel(ability, type, pl, "AidTo");
        adjConfigDestinationTree.setTreeTableModel(model2);
        
        ability.debugDetailList( "Ability Debug" ); */
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jScrollPane1.setMinimumSize(new java.awt.Dimension(200, 200));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jScrollPane2, gridBagConstraints);

        pack();
    }//GEN-END:initComponents

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        new AdjTestPanel().show();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
