/*
 * AboutDialog.java
 *
 * Created on March 14, 2001, 9:16 AM
 */

package champions;

/**
 *
 * @author  twalker
 * @version 
 */
public class AboutDialog extends javax.swing.JDialog {

    /** Creates new form AboutDialog */
    public AboutDialog(java.awt.Frame parent,boolean modal) {
        super (parent, modal);
        initComponents ();
        
        String text = textArea.getText();
        StringBuffer sb = new StringBuffer(text);
        int index = text.indexOf("$$$");
        if ( index != -1 ) {
            sb.replace( index, index + 3,CombatSimulator.getVersion());
        }
        textArea.setText( sb.toString() );
        pack ();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jButton1 = new javax.swing.JButton();
        textArea = new javax.swing.JTextArea();
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        
        jButton1.setText("Okay");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        
        getContentPane().add(jButton1, java.awt.BorderLayout.SOUTH);
        
        textArea.setWrapStyleWord(true);
        textArea.setLineWrap(true);
        textArea.setEditable(false);
        textArea.setText("Hero Combat Simulator \nVersion $$$\n\nCopyright 2001 - This program may not be used or distributed without permission.\n\nProject Manager - Pete Ruttman (pruttm@yahoo.com)\nLead Developer - Trevor Walker (trevor.walker@usa.net)\nAdditional Icons - Charlie Ball (cgball@earthlink.net)\nAdditional Icons - Dust Raven (a.k.a.) RC Craigo (dust_raven@hotmail.com)");
        textArea.setBackground(new java.awt.Color(204, 204, 204));
        textArea.setPreferredSize(new java.awt.Dimension(300, 250));
        getContentPane().add(textArea, java.awt.BorderLayout.CENTER);
        
    }//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// Add your handling code here:
      setVisible(false);
      dispose();
  }//GEN-LAST:event_jButton1ActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible (false);
        dispose ();
    }//GEN-LAST:event_closeDialog

    /**
    * @param args the command line arguments
    */
    public static void main (String args[]) {
        new AboutDialog (new javax.swing.JFrame (), true).show ();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables

}
