/*
 * PADDiceEditor.java
 *
 * Created on October 9, 2000, 2:47 PM
 */

package champions;

import champions.interfaces.PADValueListener;
import java.awt.Color;

import java.awt.event.ActionListener;

/**
 *
 * @author  unknown
 * @version
 */
public class PADStringEditor extends PADAbstractEditor {

    /** Holds value of property description. */
    private String description;
    /** Holds value of property propertyName. */
    private String propertyName;
    /** Holds value of property value. */
    private String value;
    /** Creates new form PADDiceEditor */
    public PADStringEditor() {
        initComponents ();

        setDescription("");
        setPropertyName("");

        textField.setText("");
        setValue( "" );
        
        descriptionLabel.setForeground( getForeground() );
    }
    
    public PADStringEditor(String key,String desc,PADValueListener l) {
        initComponents ();

        setDescription(desc);
        setPropertyName(key);

        textField.setText("");
        setValue( "" );

        addPADValueListener(l);
        
        descriptionLabel.setForeground( getForeground() );
    }

    public PADStringEditor(String name,String desc,String initial,PADValueListener l) {
        this(name, desc, l);

        textField.setText(initial.toString());
        setValue(initial);
    }

    public void updateValue() {
        String currentValue = textField.getText();

        setValue( currentValue );

    }
    /** Getter for property description.
     * @return Value of property description.
     */
    public String getDescription() {
        return description;
    }
    /** Setter for property description.
     * @param description New value of property description.
     */
    public void setDescription(String description) {
        this.description = description;
        descriptionLabel.setText( description );
    }
    /** Getter for property propertyName.
     * @return Value of property propertyName.
     */
    public String getPropertyName() {
        return propertyName;
    }
    /** Setter for property propertyName.
     * @param propertyName New value of property propertyName.
     */
    public void setPropertyName(String propertyName) {
        this.propertyName = propertyName;
    }
    /** Getter for property value.
     * @return Value of property value.
     */
    public String getValue() {
        return value;
    }
    /** Setter for property value.
     * @param value New value of property value.
     */
    public void setValue(String value) {
        String oldvalue = this.value;
        if ( value.equals( oldvalue ) == false && firePADValueChanging(propertyName, value, oldvalue) ) {
            this.value = value;
            textField.setText( value );
            firePADValueChanged( propertyName, value, oldvalue);
        }
        else {
            textField.setText( oldvalue );
        }
    }

    public void setValue(Object o) {
        if ( o != null && o.getClass() == String.class) {
            setValue( (String) o);
        }
    }
                
    public void setEnabled(boolean enabled) {
        super.setEnabled(enabled);
        textField.setEnabled(enabled);
        
    }
    
    public void setForeground( Color c ) {
    super.setForeground(c);
    if ( descriptionLabel != null ) descriptionLabel.setForeground(c);
}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        descriptionLabel = new javax.swing.JLabel();
        textField = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        descriptionLabel.setText("Description");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        add(descriptionLabel, gridBagConstraints);

        textField.setText("1");
        textField.setPreferredSize(new java.awt.Dimension(40, 20));
        textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldActionPerformed(evt);
            }
        });
        textField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dieTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dieTextFocusLost(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        add(textField, gridBagConstraints);

    }//GEN-END:initComponents

    private void textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldActionPerformed
        // Add your handling code here:
        updateValue();
    }//GEN-LAST:event_textFieldActionPerformed

  private void dieTextFocusGained (java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dieTextFocusGained
    // Add your handling code here:
    textField.selectAll();
  }//GEN-LAST:event_dieTextFocusGained

  private void dieTextFocusLost (java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dieTextFocusLost
    // Add your handling code here:
    updateValue();
  }//GEN-LAST:event_dieTextFocusLost
  


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextField textField;
    // End of variables declaration//GEN-END:variables


    
}