/*
 * PreferencesWindow.java
 *
 * Created on December 21, 2000, 9:27 PM
 */

package champions;

import champions.parameters.PreferenceList;
import java.awt.event.*;
import java.awt.*;
/**
 *
 * @author  unknown
 * @version
 */
public class PreferencesWindow extends javax.swing.JFrame
        implements ComponentListener{
    
    /** Creates new form PreferencesWindow */
    public PreferencesWindow() {
        initComponents();
        
        PreferencesPanel pp = new PreferencesPanel();
        pp.setWindow(this);
        pp.setPreferenceList( Preferences.getPreferenceList() );
        getContentPane().add( pp );
        pack();
        
        Object bounds = Preferences.getPreferenceList().getWindowBounds("preferencesWindow");
        if ( bounds != null ) this.setBounds( (Rectangle)bounds);
        addComponentListener(this);
    }
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        setTitle("Preferences");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

    }//GEN-END:initComponents
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        //System.exit (0);
        dispose();
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new PreferencesWindow().show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
    public void componentResized(ComponentEvent e) {
        String window = null;
        if ( e.getComponent() == this ) {
            window = "preferencesWindow";
            PreferenceList pl = Preferences.getPreferenceList();
            
            pl.setWindowBounds(window, e.getComponent().getBounds() );
        }
        
        
    }
    /** Invoked when the component's position changes.
     */
    public void componentMoved(ComponentEvent e) {
        String window = null;
        if ( e.getComponent() == this ) {
            window = "preferencesWindow";
            PreferenceList pl = Preferences.getPreferenceList();
            
            pl.setWindowBounds(window, e.getComponent().getBounds() );
        }
    }
    /** Invoked when the component has been made visible.
     */
    public void componentShown(ComponentEvent e) {
    }
    /** Invoked when the component has been made invisible.
     */
    public void componentHidden(ComponentEvent e) {
    }
}