/*
 * TargetEditorAbilityPanel.java
 *
 * Created on September 10, 2001, 11:41 AM
 */

package champions;

import java.awt.*;
import javax.swing.*;

import tjava.Destroyable;
/**
 *
 * @author  twalker
 */
public class TargetEditorAbilityPanel extends javax.swing.JPanel
implements Destroyable {

    /** Creates new form TargetEditorAbilityPanel */
    public TargetEditorAbilityPanel() {
        initComponents();
        abilityTree.setScrollPane(abilityScroll);
    }
    
    public Dimension getPreferredSize() {
        Dimension d = abilityTree.getPreferredSize();
        if ( d.width < 350 ) d.width = 350;
        if ( d.width > 500 ) d.width = 500;
        return d;
    }
    
    public JTree getTree() {
        return abilityTree;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        abilityScroll = new javax.swing.JScrollPane();
        abilityTree = new champions.abilityTree.AbilityTreeTable();

        setLayout(new java.awt.BorderLayout());

        abilityTree.setAutoResizeMode(2);
        abilityTree.setOpaque(false);
        abilityScroll.setViewportView(abilityTree);

        add(abilityScroll, java.awt.BorderLayout.CENTER);

    }
    // </editor-fold>//GEN-END:initComponents

    /** Getter for property target.
     * @return Value of property target.
     */
    public Target getTarget() {
        return target;
    }    

    /** Setter for property target.
     * @param target New value of property target.
     */
    public void setTarget(Target target) {
        this.target = target;
        abilityTree.setTarget(target);
        
        abilityTree.selectNode("Powers");
    }    

    public void destroy() {
        removeAll();
        abilityTree.destroy();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane abilityScroll;
    private champions.abilityTree.AbilityTreeTable abilityTree;
    // End of variables declaration//GEN-END:variables

    /** Holds value of property target. */
    private Target target;    

}
