/*
 * GenericAbilityConfigurePanel.java
 *
 * Created on October 31, 2001, 11:53 PM
 */

package champions.attackTree;

import champions.Target;
import champions.interfaces.ChampionsConstants;
import champions.interfaces.Framework;
import javax.swing.JPanel;

/**
 *
 * @author  twalker
 */
public class ConfigureFrameworkSetupPanel extends JPanel implements AttackTreeInputPanel, ChampionsConstants {
    /** Stores a cached GenericAbilityConfigurePanel which can be reused. */
    static protected ConfigureFrameworkSetupPanel ad = null;
    
    protected AttackTreePanel atip;
    
    /** Creates new form GenericAbilityConfigurePanel */
    public ConfigureFrameworkSetupPanel() {
        initComponents();
        setupActions();
    }
    
    public void setupActions() {
        
    }
    
    static public ConfigureFrameworkSetupPanel getGenericAbilityConfigurePanel(Target target, Framework framework) {
        if ( ad == null ) ad = new ConfigureFrameworkSetupPanel();
        
        ad.setup(target, framework);
        
        return ad;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        vppConfigurationPanel = new champions.VPPConfigurationPanel();

        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(vppConfigurationPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
                                
    public void showPanel(AttackTreePanel atip) {
        this.atip = atip;
    }
    
    public JPanel getPanel() {
        return this;
    }
    
    public void hidePanel() {
    }

    protected void setup(Target target, Framework framework) {
        vppConfigurationPanel.setup(target, framework);
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private champions.VPPConfigurationPanel vppConfigurationPanel;
    // End of variables declaration//GEN-END:variables
    
}
