/*
 * DefensesPanel.java
 *
 * Created on November 21, 2001, 10:11 PM
 */

package champions.attackTree;

import champions.DefenseList;
import champions.Target;
import javax.swing.JPanel;

/**
 *
 * @author  twalker
 */
public class DefensesPanel extends JPanel implements AttackTreeInputPanel {

    protected static DefensesPanel defaultPanel;
    
    /** Holds value of property defenseList. */
    private DefenseList defenseList;
    
    /** Creates new form DefensesPanel */
    public DefensesPanel() {
        initComponents();
    }
    
    static public DefensesPanel getDefaultPanel(Target target, DefenseList defenseList) {
        if ( defaultPanel == null ) defaultPanel = new DefensesPanel();
        
        defaultPanel.setTarget(target);
        defaultPanel.setDefenseList(defenseList);
        
        return defaultPanel;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        defensePanel = new champions.DefensePanel();

        defensePanel.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(defensePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(defensePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void showPanel(AttackTreePanel atip) {
    }    

    public JPanel getPanel() {
        return this;
    }    

    public void hidePanel() {
    }
    
    /** Getter for property defenseList.
     * @return Value of property defenseList.
     */
    public DefenseList getDefenseList() {
        return defenseList;
    }
    
    /** Setter for property defenseList.
     * @param defenseList New value of property defenseList.
     */
    public void setDefenseList(DefenseList defenseList) {
        this.defenseList = defenseList;
        defensePanel.setDefenseList(defenseList);
    }
    
    /** Getter for property target.
     * @return Value of property target.
     */
    private Target getTarget() {
        return target;
    }
    
    /** Setter for property target.
     * @param target New value of property target.
     */
    private void setTarget(Target target) {
        this.target = target;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private champions.DefensePanel defensePanel;
    // End of variables declaration//GEN-END:variables

    /** Holds value of property target. */
    private Target target;    

}
