/*
 * InformationPanel.java
 *
 * Created on December 17, 2001, 11:56 AM
 */

package champions.attackTree;

import champions.Target;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 *
 * @author  twalker
 */
public class InformationPanel extends JPanel implements AttackTreeInputPanel{

    static private InformationPanel defaultPanel;
    
    /** Holds value of property text. */
    private String text;
    
    /** Creates new form InformationPanel */
    public InformationPanel() {
        initComponents();
    }
    
    static public InformationPanel getDefaultPanel(String text) {
        if ( defaultPanel == null ) defaultPanel = new InformationPanel();
        
        defaultPanel.setText(text);
        
        return defaultPanel;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        infoTextArea = new javax.swing.JTextArea();

        setLayout(new java.awt.GridBagLayout());

        infoTextArea.setBackground(new java.awt.Color(204, 204, 204));
        infoTextArea.setEditable(false);
        infoTextArea.setFont(UIManager.getFont("CombatSimulator.defaultFont"));
        infoTextArea.setLineWrap(true);
        infoTextArea.setText("test");
        infoTextArea.setWrapStyleWord(true);
        infoTextArea.setFocusable(false);
        infoTextArea.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(infoTextArea, gridBagConstraints);

    }// </editor-fold>//GEN-END:initComponents

    public Target getAutoBypassTarget() {
        return null;
    }    

    public void showPanel(AttackTreePanel atip) {
        
    }    

    public String getAutoBypassOption() {
        return null;
    }
    
    public JPanel getPanel() {
        return this;
    }
    
    public void hidePanel() {
    }
    
    /** Getter for property text.
     * @return Value of property text.
     */
    public String getText() {
        return text;
    }
    
    /** Setter for property text.
     * @param text New value of property text.
     */
    public void setText(String text) {
        this.text = text;
        infoTextArea.setText(text);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea infoTextArea;
    // End of variables declaration//GEN-END:variables

}
