/*
 * MessagePanel.java
 *
 * Created on December 24, 2001, 1:34 PM
 */

package champions.attackTree;

import champions.BattleEvent;
import champions.Target;
import javax.swing.JPanel;

/**
 *
 * @author  twalker
 */
public class MessagePanel extends JPanel implements AttackTreeInputPanel {
     
     static private MessagePanel defaultPanel = null;

     /** Holds value of property battleEvent. */
     private BattleEvent battleEvent;
     
     /** Holds value of property target. */
     private Target target;
     
     /** Holds value of property start. */
     private int start;
     
     /** Holds value of property end. */
     private int end;
     
    /** Creates new form MessagePanel */
    public MessagePanel() {
        initComponents();
    }
    
        static public MessagePanel getDefaultPanel(BattleEvent battleEvent, Target target, int start, int end) {
        if ( defaultPanel == null ) defaultPanel = new MessagePanel();
        
        defaultPanel.setBattleEvent(battleEvent);
        defaultPanel.setTarget(target);
        defaultPanel.setStart(start);
        defaultPanel.setEnd(end);
        
        return defaultPanel;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        battleEventScroll = new javax.swing.JScrollPane();
        battleEventArea = new champions.MessageArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        battleMessageTree = new champions.abilityTree2.ATBattleMessageTree();

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        battleEventScroll.setViewportView(battleEventArea);

        jSplitPane1.setLeftComponent(battleEventScroll);

        jScrollPane2.setViewportView(battleMessageTree);

        jSplitPane1.setBottomComponent(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

   

    public void showPanel(AttackTreePanel atip) {
        
    }    


    
    public JPanel getPanel() {
        return this;
    }
    
    public void hidePanel() {
        setTarget(null);
    }
    
    /** Getter for property battleEvent.
     * @return Value of property battleEvent.
     */
    public BattleEvent getBattleEvent() {
        return battleEvent;
    }
    
    /** Setter for property battleEvent.
     * @param battleEvent New value of property battleEvent.
     */
    public void setBattleEvent(BattleEvent battleEvent) {
        this.battleEvent = battleEvent;
        battleEventArea.setBattleEvent(battleEvent);
        battleMessageTree.setPrimaryBattleMessage( battleEvent.getPrimaryBattleMessageGroup() );
    }
    
    /** Getter for property target.
     * @return Value of property target.
     */
    public Target getTarget() {
        return target;
    }
    
    /** Setter for property target.
     * @param target New value of property target.
     */
    public void setTarget(Target target) {
        this.target = target;
    }
    
    /** Getter for property start.
     * @return Value of property start.
     */
    public int getStart() {
        return start;
    }
    
    /** Setter for property start.
     * @param start New value of property start.
     */
    public void setStart(int start) {
        this.start = start;
        battleEventArea.setStartMessage(start);
    }
    
    /** Getter for property end.
     * @return Value of property end.
     */
    public int getEnd() {
        return end;
    }
    
    /** Setter for property end.
     * @param end New value of property end.
     */
    public void setEnd(int end) {
        this.end = end;
        battleEventArea.setEndMessage(end);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private champions.MessageArea battleEventArea;
    private javax.swing.JScrollPane battleEventScroll;
    private champions.abilityTree2.ATBattleMessageTree battleMessageTree;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables

}
