/*
 * RealTreePanel.java
 *
 * Created on November 13, 2003, 1:16 AM
 */

package champions.attackTree;

import tjava.ContextMenu;
import tjava.ContextMenuListener;
import java.awt.Component;
import champions.Battle;
import java.awt.Point;
import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.tree.TreeCellRenderer;
import javax.swing.tree.TreeModel;
import javax.swing.tree.TreePath;

/**
 *
 * @author  1425
 */
public class ScrollableTreePanel extends JPanel
implements ContextMenuListener {
    
    
    /** Creates new form RealTreePanel */
    public ScrollableTreePanel(TreeModel model, TreeCellRenderer renderer) {
        initComponents();
        jTree1.setModel( model);
        
        ContextMenu.addContextMenu(jTree1);
        
        if ( renderer != null ) {
            jTree1.setCellRenderer(renderer);
        }
        
        expandAll();
    }
    
    public static void showTreePanel(TreeModel model) {
        showTreePanel(model, null);
    }
    
    public static void showTreePanel(TreeModel model, TreeCellRenderer renderer) {
        JFrame frame = new JFrame();
        frame.getContentPane().add( new ScrollableTreePanel(model, renderer) );
        frame.pack();
        
        frame.show();
    }
    
    public void expandAll() {
        expandAll( new TreePath( jTree1.getModel().getRoot() ) );
    }
    
    public void expandAll(TreePath path) {
        
        jTree1.expandPath(path);
        
        Object node = path.getLastPathComponent();
        int count = jTree1.getModel().getChildCount( node );
        for(int index = 0; index < count; index++) {
            TreePath newPath = path.pathByAddingChild( jTree1.getModel().getChild(node, index));
            expandAll( newPath);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();

        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(jTree1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents

    public boolean invokeMenu(JPopupMenu popup, Component inComponent, Point inPoint) {
        TreePath tp = jTree1.getSelectionPath();
        if ( tp != null && Battle.debugLevel >= 1) {
            if ( tp.getLastPathComponent() instanceof AttackTreeNode ) {
                final AttackTreeNode atn = (AttackTreeNode)tp.getLastPathComponent();
                popup.add( new AbstractAction("Debug Node's BattleEvent") {
                    public void actionPerformed(ActionEvent e ) {
                        atn.getBattleEvent().debugDetailList(atn.getName() + "'s BattleEvent");
                    }
                });
                return true;
            }
        }
        return false;
    }    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
    
}
