/*
 * TreeTableTest.java
 *
 * Created on February 17, 2002, 3:59 PM
 */

package treeTable;


/**
 *
 * @author  twalker
 */
public class TreeTableTest extends javax.swing.JFrame {

    /** Creates new form TreeTableTest */
    public TreeTableTest() {
      //  UIManager.put("TreeTableHeaderUI", "treeTable.BasicTreeTableHeaderUI");
        
        initComponents();
        
      //  TreeTable tt = new TreeTable();
        
     //   jScrollPane1.setViewportView( tt );
     //  pack();
        
        SimpleTreeTableNode root = new SimpleTreeTableNode( new Object[] {"Root", "A", new Integer(1) } );
        root.add( new SimpleTreeTableNode( new Object[] {"Node A", "B", new Integer(1) } ) );
        SimpleTreeTableNode n2 = new SimpleTreeTableNode( new Object[] {"Node B", "C", new Integer(2) } );
        root.add( n2 );
        
        n2.add( new SimpleTreeTableNode( new Object[] {"Node C", "D", new Integer(3) } ) );
        
//        ParameterList pl =new ParameterList();
//        pl.addIntegerParameter( "TestParam", "Test.PARAM", "Test Param", new Integer(1) );
//        
//        
//        n2.add( new ParameterTreeTableNode( pl, "TestParam"));
        
        SimpleTreeTableModel m = new SimpleTreeTableModel( root );
        
        treeTable1.setTreeTableModel( m );
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jScrollPane1 = new javax.swing.JScrollPane();
        treeTable1 = new treeTable.TreeTable();
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        
        jScrollPane1.setViewportView(treeTable1);
        
        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);
        
        pack();
    }//GEN-END:initComponents

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        new TreeTableTest().show();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private treeTable.TreeTable treeTable1;
    // End of variables declaration//GEN-END:variables

}
